# Generated by Django 3.1.2 on 2021-07-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.city'),
            preserve_default=False,
        ),
    ]
