# Generated by Django 3.1.2 on 2021-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_city_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
