# Generated by Django 3.1.2 on 2021-07-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_stock',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
