# Generated by Django 3.1.2 on 2021-07-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productdetail_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_key',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_key',
            field=models.ForeignKey(default=137, on_delete=django.db.models.deletion.CASCADE, to='product.addtocard'),
            preserve_default=False,
        ),
    ]
