# Generated by Django 3.1.2 on 2021-07-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_key',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_key',
            field=models.ManyToManyField(to='product.AddToCard'),
        ),
    ]
