# Generated by Django 3.1.2 on 2021-07-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_key',
        ),
        migrations.AddField(
            model_name='order',
            name='product_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productdetail'),
            preserve_default=False,
        ),
    ]
