# Generated by Django 3.1.2 on 2021-07-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210722_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.addtocard'),
        ),
    ]
