# Generated by Django 3.1.2 on 2021-07-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productdetail_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category_key',
        ),
    ]
