# Generated by Django 3.1.2 on 2021-07-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_brand_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product_brand',
        ),
    ]
