# Generated by Django 3.1.2 on 2021-07-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productdetail_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product_brand',
        ),
    ]
