# Generated by Django 3.1.2 on 2021-07-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_productdetail_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
            preserve_default=False,
        ),
    ]
